import type { Suite, Workflow } from "@pathsmith/contracts";
import { LogoMark } from "./AppShell";
import { ModeBadge, Panel, StatusPill, StepBar } from "./ScreenUi";
import type { Case, Draft, Run } from "./screenTypes";

type Props = {
  projectId: string; projects: { id: string; name: string }[]; examples: { id: string; name: string; fixtureSetId: string }[];
  workflowDraft: Draft<Workflow> | null; suiteDraft: Draft<Suite> | null; workflowVersionId: string; suiteVersionId: string;
  runs: Run[]; busy: boolean; fileMessage: string; fileAck: boolean; onFileAck: (value: boolean) => void;
  onOpenProject: (id: string) => Promise<void>; onLoadStarter: () => Promise<void>; onLoadExample: (id: string) => Promise<void>;
  onImportFile: (file?: File) => Promise<void>; onExportFile: () => Promise<void>;
  onStep: (step: number) => void; onOpenRun: (id: string) => void; onWorkflow: () => void; onCompare: () => void;
};
const runStatus = (status: string) => status === "completed" ? "success" : status === "failed" ? "error" : status === "canceled" || status === "interrupted" ? "warn" : "accent";
export function OverviewScreen(props: Props) {
  const project = props.projects.find((item) => item.id === props.projectId);
  const cases = (Array.isArray(props.suiteDraft?.definition.scenarios) ? props.suiteDraft.definition.scenarios.filter((item): item is Case => !!item && typeof item === "object") : []) as Case[];
  const classification = !!props.suiteDraft?.definition.classification;
  const reviewed = cases.filter((item) => item.referenceLabel?.review === "reviewed" && item.referenceLabel.value !== null).length;
  const unresolved = classification ? cases.filter((item) => !item.referenceLabel || item.referenceLabel.review !== "reviewed" || item.referenceLabel.value === null).length : 0;
  const draftProblems = [...(props.workflowDraft?.diagnostics ?? []), ...(props.suiteDraft?.diagnostics ?? [])];
  const step = !project ? 0 : !props.suiteVersionId ? 0 : unresolved > 0 ? 1 : props.runs.length ? 3 : 2;
  if (!project) return <div className="overview-start"><LogoMark size={32} /><h1>Start a local project</h1><p>Build a workflow, publish a labeled test set, run it, and inspect saved results.</p><div className="overview-start-grid"><Panel><div className="panel-body"><strong>Classification starter</strong><p>A known synthetic example with exact mock responses. Load it as a new local project.</p><button className="primary-action" disabled={props.busy} onClick={() => void props.onLoadStarter()}>Create from starter</button></div></Panel><Panel><div className="panel-body"><strong>Open an existing project</strong><label>Saved project<select aria-label="Saved project" value="" onChange={(event) => void props.onOpenProject(event.target.value)}><option value="">Choose project</option>{props.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{props.projects.length === 0 && <p>No saved projects yet.</p>}</div></Panel></div><div className="overview-import"><label className="button">Import project JSON<input type="file" accept=".json,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void props.onImportFile(file); event.target.value = ""; }} /></label>{props.fileMessage && <p role="status">{props.fileMessage}</p>}</div></div>;
  return <div className="overview-screen">
    <div className="overview-welcome"><span>Welcome back</span><h1>{project.name}</h1><dl className="overview-fact-grid"><div><dt>Workflow</dt><dd>{props.workflowDraft?.name ?? "No workflow draft"} {props.workflowVersionId && <code>{props.workflowVersionId.slice(0, 8)}</code>}</dd></div><div><dt>Test set</dt><dd>{props.suiteDraft?.name ?? "No test set draft"} {props.suiteVersionId && <code>{props.suiteVersionId.slice(0, 8)}</code>}</dd></div><div><dt>Examples</dt><dd>{classification ? `${cases.length} · ${reviewed} reviewed` : `${cases.length} cases`}</dd></div><div><dt>Last run</dt><dd>{props.runs[0] ? <ModeBadge mode={props.runs[0].mode} /> : "None yet"}</dd></div></dl></div>
    {draftProblems.length > 0 && <div className="screen-banner tone-warn" role="status"><StatusPill kind="warn">Draft needs attention</StatusPill><span>{draftProblems.length} diagnostics. Imported drafts stay editable; validate and publish before running.</span><button onClick={props.onWorkflow}>Open workflow</button></div>}
    <div className="overview-next"><div className="overview-next-top"><div><h2>Resume where you left off</h2><p>{!props.workflowVersionId ? "Validate and save a workflow version before running." : !props.suiteVersionId ? "Publish a test-set version before running." : unresolved ? `${unresolved} of ${cases.length} references are provisional, unclear, or unlabeled. Review them when you can.` : props.runs.length ? `The latest run saved ${props.runs[0].progress.persisted} of ${props.runs[0].progress.selected} case results. Inspect its trace or compare runs.` : `${cases.length} examples are ready in the published test set.`}</p></div><button className="primary-action" onClick={() => !props.workflowVersionId ? props.onWorkflow() : props.onStep(step)}>{!props.workflowVersionId ? "Open workflow" : step === 3 ? "Inspect results" : step === 2 ? "Run test set" : step === 1 ? "Review labels" : "Open test set"}</button></div><div className="overview-stepper"><StepBar step={step} onStep={props.onStep} /></div><div className="inline-actions"><button onClick={props.onWorkflow}>Open workflow</button><button onClick={props.onCompare}>Compare runs</button></div></div>
    <div className="overview-recent"><div className="overview-section-head"><h2>Recent runs</h2><span>Saved locally · immutable snapshots</span></div>{props.runs.length ? <ul className="overview-run-rows">{props.runs.slice(0, 5).map((item) => <li key={item.id}><button onClick={() => props.onOpenRun(item.id)}><code>{item.id.slice(0, 8)}</code><ModeBadge mode={item.mode} /><span>{item.progress.persisted} of {item.progress.selected} persisted · {item.summary.completed} completed</span><StatusPill kind={runStatus(item.status)}>{item.status}</StatusPill><time>{new Date(item.createdAt).toLocaleString()}</time><span aria-hidden="true">›</span></button></li>)}</ul> : <div className="screen-empty-small">No runs yet. The first executed run will appear here.</div>}</div>
    <details className="secondary-tools overview-project-tools"><summary>Project and file tools</summary><div className="panel-body"><label>Switch project<select value={props.projectId} onChange={(event) => void props.onOpenProject(event.target.value)}>{props.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Load another example<select defaultValue="" onChange={(event) => { if (event.target.value) void props.onLoadExample(event.target.value); event.target.value = ""; }}><option value="">Choose example</option>{props.examples.map((item) => <option key={item.id} value={item.id}>{item.name} · known fixture</option>)}</select></label><label className="button">Import project JSON<input type="file" accept=".json,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void props.onImportFile(file); event.target.value = ""; }} /></label><label className="check"><input type="checkbox" checked={props.fileAck} onChange={(event) => props.onFileAck(event.target.checked)} /> Export includes workflow and test-set drafts, which may contain sensitive inputs.</label><button disabled={!props.fileAck || props.busy} onClick={() => void props.onExportFile()}>Export project JSON</button>{props.fileMessage && <p role="status">{props.fileMessage}</p>}</div></details>
  </div>;
}
